/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* OpenAPI spec version: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.myapplication.retrofit.model


/**
 * 
 * @param id 
 * @param login 
 * @param avatar_url 
 * @param created_at 
 * @param updated_at 
 */
data class UserRaw (
    val id: kotlin.Long? = null,
    val login: kotlin.String? = null,
    val avatar_url: kotlin.String? = null,
    val created_at: kotlin.String? = null,
    val updated_at: kotlin.String? = null
) {

}

